const resorts = [
    // ==========================================
    // --- ÖSTERREICH ---
    // ==========================================
    { 
        id: 1, 
        name: "Ski Arlberg", 
        searchTerms: "warth schröcken lech zürs stuben st. christoph st. anton", 
        coords: [47.1296, 10.2681], 
        pisteKm: 305, 
        lifts: 88, 
        elevation: 2811, 
        priceLevel: 3, 
        skipass: "85 €", 
        img: "bilder/arlberg.jpg", 
        pisteMap: "bilder/arlberg-map.jpg", 
        website: "https://www.skiarlberg.at", 
        highlights: "Das größte zusammenhängende Skigebiet Österreichs. Legendäres Tiefschnee-Mekka und Wiege des alpinen Skisports.", 
        tags: ["Österreich", "Après-Ski", "Schneesicher", "Off-Piste", "Großes Skigebiet", "moderne Liftanlagen"] 
    },
    { id: 2, name: "Ischgl (Silvretta Arena)", coords: [47.0116, 10.2872], pisteKm: 239, lifts: 45, elevation: 2872, priceLevel: 3, skipass: "76 €", img: "bilder/ischgl.jpg", pisteMap: "bilder/ischgl-map.jpg", website: "https://www.ischgl.com", highlights: "Die Lifestyle-Metropole der Alpen. Riesiges grenzübergreifendes Pistenangebot.", tags: ["Österreich", "Schweiz", "Après-Ski", "Schneesicher", "moderne Liftanlagen", "Snowpark"] },
    { id: 3, name: "Sölden", coords: [46.9655, 11.0079], pisteKm: 144, lifts: 31, elevation: 3340, priceLevel: 3, skipass: "80 €", img: "bilder/soelden.jpg", pisteMap: "bilder/soelden-map.jpg", website: "https://www.soelden.com", highlights: "Gletscher-Skifahren auf über 3.000m. Drehort von James Bond 'Spectre'.", tags: ["Österreich", "Gletscher", "Schneesicher", "Weltcup" , "Snowpark"] },
    { id: 5, name: "Obertauern", coords: [47.2479, 13.5350], pisteKm: 100, lifts: 26, elevation: 2313, priceLevel: 2, skipass: "63 €", img: "bilder/obertauern.jpg", pisteMap: "bilder/obertauern-map.jpg", website: "https://www.obertauern.com", highlights: "Die Schneeschüssel Österreichs. Dank der Kessellage absolute Schneesicherheit.", tags: ["Österreich", "Schneesicher", "Après-Ski", "Günstig", "Familien"] },
    { id: 6, name: "Serfaus-Fiss-Ladis", coords: [47.0384, 10.6074], pisteKm: 214, lifts: 68, elevation: 2828, priceLevel: 3, skipass: "73 €", img: "bilder/serfaus.jpg", pisteMap: "bilder/serfaus-map.jpg", website: "https://www.serfaus-fiss-ladis.at", highlights: "Das familienfreundlichste Skigebiet der Alpen. Mit erstklassigen Skischulen auf höchstem Niveau.", tags: ["Österreich", "Familien", "Großes Skigebiet", "moderne Liftanlagen", "Snowpark" ] },
    { id: 9, name: "Schladming (4-Berge)", coords: [47.3934, 13.6848], pisteKm: 123, lifts: 44, elevation: 2015, priceLevel: 2, skipass: "76 €", img: "bilder/schladming.jpg", pisteMap: "bilder/schladming-map.jpg", website: "https://www.schladming-dachstein.at", highlights: "Legendär durch das Nightrace auf der Planai. Vier verbundene Berge bieten pausenloses Skivergnügen.", tags: ["Österreich", "Weltcup", "Après-Ski", "Hütten"] },
    { id: 10, name: "Wagrain (Snow Space)", coords: [47.3323, 13.3032], pisteKm: 210, lifts: 70, elevation: 1980, priceLevel: 2, skipass: "76 €", img: "bilder/wagrain.jpg", pisteMap: "bilder/wagrain-map.jpg", website: "https://www.snow-space.com", highlights: "Das Herz von Ski amadé. Top-moderne Seilbahnen wie der G-Link und fantastische Bedingungen.", tags: ["Österreich", "Familien", "Großes Skigebiet", "moderne Liftanlagen"] },
    { id: 11, name: "Kitzsteinhorn (Kaprun)", coords: [47.2023, 12.6974], pisteKm: 61, lifts: 23, elevation: 3029, priceLevel: 2, skipass: "76 €", img: "bilder/kitzsteinhorn.jpg", pisteMap: "bilder/kitzsteinhorn-map.jpg", website: "https://www.kitzsteinhorn.at", highlights: "Der Gletscher im Salzburger Land. Fantastische Freeride-Routen und 100% Schneesicherheit.", tags: ["Österreich", "Gletscher", "Schneesicher", "Snowpark"] },
    { id: 12, name: "Saalbach-Hinterglemm", coords: [47.3934, 12.6366], pisteKm: 270, lifts: 70, elevation: 2096, priceLevel: 2, skipass: "76 €", img: "bilder/saalbach.jpg", pisteMap: "bilder/saalbach-map.jpg", website: "https://www.saalbach.com", highlights: "Der Skicircus gehört zu den größten Skigebieten Österreichs. Endlose Pisten und top Hütten.", tags: ["Österreich", "Großes Skigebiet", "Après-Ski", "Hütten"] },
    { id: 13, name: "Kitzbühel", coords: [47.4462, 12.3926], pisteKm: 234, lifts: 57, elevation: 2000, priceLevel: 3, skipass: "76 €", img: "bilder/kitzbuehel.jpg", pisteMap: "bilder/kitzbuehel-map.jpg", website: "https://www.kitzski.at", highlights: "Die Heimat der legendären Streif. Edler Wintersportort mit herausragender Pistenpräparierung.", tags: ["Österreich", "Weltcup", "Großes Skigebiet", "Snowpark"] },
    { id: 14, name: "Zillertal Arena", coords: [47.2341, 11.8845], pisteKm: 150, lifts: 52, elevation: 2500, priceLevel: 2, skipass: "76 €", img: "bilder/zillertal-arena.jpg", pisteMap: "bilder/zillertal-arena-map.jpg", website: "https://www.zillertalarena.com", highlights: "Das größte Skigebiet im Zillertal. Von Zell am Ziller bis nach Gerlos ein echtes Pistenparadies.", tags: ["Österreich", "Familien", "Großes Skigebiet", "Hütten"] },
    { id: 15, name: "Hintertuxer Gletscher", coords: [47.0754, 11.6789], pisteKm: 60, lifts: 21, elevation: 3250, priceLevel: 2, skipass: "76 €", img: "bilder/hintertux.jpg", pisteMap: "bilder/hintertux-map.jpg", website: "https://www.hintertuxergletscher.at", highlights: "Österreichs einziges Ganzjahresskigebiet. Training-Spot für Profiteams aus aller Welt.", tags: ["Österreich", "Gletscher", "Schneesicher", "Weltcup"] },
    { id: 16, name: "Skiwelt Wilder Kaiser", coords: [47.4984, 12.1969], pisteKm: 288, lifts: 90, elevation: 1957, priceLevel: 2, skipass: "69 €", img: "bilder/skiwelt.jpg", pisteMap: "bilder/skiwelt-map.jpg", website: "https://www.skiwelt.at", highlights: "Eines der größten Skigebiete weltweit. Bekannt für wahnsinnig viele urgemütliche Hütten.", tags: ["Österreich", "Großes Skigebiet", "Familien", "Hütten"] },
    { id: 17, name: "Stubaier Gletscher", coords: [46.9942, 11.1396], pisteKm: 64, lifts: 26, elevation: 3210, priceLevel: 2, skipass: "68 €", img: "bilder/stubaier-gletscher.jpg", pisteMap: "bilder/stubaier-gletscher-map.jpg", website: "https://www.stubaier-gletscher.com", highlights: "Das größte Gletscher-Skigebiet Österreichs. Sehr familienfreundlich.", tags: ["Österreich", "Gletscher", "Familien"] },
    { id: 18, name: "Pitztaler Gletscher", coords: [46.9318, 10.8711], pisteKm: 41, lifts: 7, elevation: 3440, priceLevel: 2, skipass: "68 €", img: "bilder/pitztal.jpg", pisteMap: "bilder/pitztal-map.jpg", website: "https://www.pitztaler-gletscher.at", highlights: "Höchstes Skigebiet in Österreich. Tolles Panorama vom Café 3.440 und extreme Schneesicherheit.", tags: ["Österreich", "Gletscher", "Schneesicher"] },
    { id: 20, name: "Damüls-Mellau", coords: [47.2818, 9.8913], pisteKm: 109, lifts: 29, elevation: 2050, priceLevel: 1, skipass: "66 €", img: "bilder/damuels.jpg", pisteMap: "bilder/damuels-map.jpg", website: "https://www.damuels-mellau.at", highlights: "Gilt als das schneereichste Dorf der Welt. Verbindet traumhafte Hänge im Bregenzerwald.", tags: ["Österreich", "Schneesicher", "Off-Piste"] },
    { id: 21, name: "Montafon (Silvretta)", coords: [47.0542, 9.9404], pisteKm: 140, lifts: 36, elevation: 2430, priceLevel: 2, skipass: "75 €", img: "bilder/montafon.jpg", pisteMap: "bilder/montafon-map.jpg", website: "https://www.silvretta-montafon.at", highlights: "Sportlichstes Skigebiet in Vorarlberg. Bietet einige extrem steile Herausforderungen.", tags: ["Österreich", "Familien", "Großes Skigebiet"] },
    { id: 45, name: "Obergurgl-Hochgurgl", coords: [46.8703, 11.0269], pisteKm: 112, lifts: 25, elevation: 3082, priceLevel: 3, skipass: "76 €", img: "bilder/obergurgl.jpg", pisteMap: "bilder/obergurgl-map.jpg", website: "https://www.obergurgl.com", highlights: "Der 'Diamant der Alpen'. Extrem hohe Schneesicherheit am Ende des Ötztals ohne Gletscher.", tags: ["Österreich", "Schneesicher", "Familien"] },
    { id: 62, name: "Bad Gastein (Ski amadé)", coords: [47.1145, 13.1345], pisteKm: 208, lifts: 45, elevation: 2686, priceLevel: 2, skipass: "76 €", img: "bilder/badgastein.jpg", pisteMap: "bilder/badgastein-map.jpg", website: "https://www.skigastein.com", highlights: "Skifahren und Thermalbaden im historischen Weltkurort der Belle Époque.", tags: ["Österreich", "Hütten", "Großes Skigebiet"] },
    { id: 63, name: "Mölltaler Gletscher", coords: [47.0142, 13.0039], pisteKm: 17, lifts: 9, elevation: 3122, priceLevel: 2, skipass: "65 €", img: "bilder/moelltal.jpg", pisteMap: "bilder/moelltal-map.jpg", website: "https://www.moelltaler-gletscher.at", highlights: "Das einzige Gletscherskigebiet in Kärnten. Perfekt für das Training im Frühherbst.", tags: ["Österreich", "Gletscher", "Schneesicher", "klein"] },
    { id: 64, name: "Zell am See (Schmittenhöhe)", coords: [47.3235, 12.7968], pisteKm: 77, lifts: 28, elevation: 2000, priceLevel: 2, skipass: "76 €", img: "bilder/zell.jpg", pisteMap: "bilder/zell-map.jpg", website: "https://www.zellamsee-kaprun.com", highlights: "Traumhafter Seeblick beim Skifahren und direkte Anbindung zum Kitzsteinhorn.", tags: ["Österreich", "Familien", "Sonnig"] },
    { id: 65, name: "Hochkönig", coords: [47.3871, 13.0583], pisteKm: 120, lifts: 34, elevation: 1900, priceLevel: 2, skipass: "76 €", img: "bilder/hochkoenig.jpg", pisteMap: "bilder/hochkoenig-map.jpg", website: "https://www.hochkoenig.at", highlights: "Teil der berühmten Königstour mit unglaublichem Panorama und unzähligen urigen Almhütten.", tags: ["Österreich", "Hütten", "moderne Liftanlagen"] },
    { id: 66, name: "Bad Kleinkirchheim", coords: [46.8143, 13.7915], pisteKm: 103, lifts: 24, elevation: 2055, priceLevel: 2, skipass: "65 €", img: "bilder/bkk.jpg", pisteMap: "bilder/bkk-map.jpg", website: "https://www.badkleinkirchheim.com", highlights: "Weltcup-Abfahrt 'Franz Klammer' und Thermalbäder direkt im Tal.", tags: ["Österreich", "Weltcup", "Familien"] },
    { id: 67, name: "Steinplatte - Waidring", coords: [47.6074, 12.5705], pisteKm: 42, lifts: 13, elevation: 1860, priceLevel: 1, skipass: "60 €", img: "bilder/steinplatte.jpg", pisteMap: "bilder/steinplatte-map.jpg", website: "https://www.steinplatte.tirol", highlights: "Besonders sonnig auf einem Hochplateau gelegen, perfekt für Familien und Genießer.", tags: ["Österreich", "Deutschland", "Sonnig", "Familien"] },
    { id: 68, name: "Kaunertaler Gletscher", coords: [46.8776, 10.7161], pisteKm: 55, lifts: 9, elevation: 3113, priceLevel: 2, skipass: "65 €", img: "bilder/kaunertal.jpg", pisteMap: "bilder/kaunertal-map.jpg", website: "https://www.kaunertaler-gletscher.at", highlights: "Ein Geheimtipp für Freerider, Anfahrt über die atemberaubende Gletscherstraße.", tags: ["Österreich", "Gletscher", "Schneesicher", "Off-Piste"] },
    { id: 69, name: "Kühtai", coords: [47.2119, 11.0205], pisteKm: 47, lifts: 12, elevation: 2520, priceLevel: 2, skipass: "56 €", img: "bilder/kuehtai.jpg", pisteMap: "bilder/kuehtai-map.jpg", website: "https://www.kuehtai.info", highlights: "Österreichs höchstgelegener Skiort. Ski-in/Ski-out bei absoluter Schneesicherheit.", tags: ["Österreich", "Schneesicher", "Hütten"] },
    { id: 70, name: "Ehrwalder Alm", coords: [47.3826, 10.9419], pisteKm: 27, lifts: 7, elevation: 1923, priceLevel: 1, skipass: "58 €", img: "bilder/ehrwald.jpg", pisteMap: "bilder/ehrwald-map.jpg", website: "https://www.almbahn.tirol", highlights: "Besonders flache und anfängerfreundliche Hänge mit gigantischem Blick auf die Zugspitze.", tags: ["Österreich", "klein", "Familien", "Günstig"] },
    { id: 97, name: "Ifen (Kleinwalsertal)", coords: [47.3453, 10.0827], pisteKm: 25, lifts: 4, elevation: 2228, priceLevel: 2, skipass: "69 €", img: "bilder/ifen.jpg", pisteMap: "bilder/ifen-map.jpg", website: "https://www.ok-bergbahnen.com", highlights: "Markantes Felsmassiv und moderne Bahnen. Wunderschöne breite Pisten auf dem Gottesackerplateau.", tags: ["Österreich", "Deutschland", "klein", "moderne Liftanlagen"] },
    { id: 98, name: "Axamer Lizum", coords: [47.1950, 11.2825], pisteKm: 40, lifts: 10, elevation: 2340, priceLevel: 2, skipass: "63 €", img: "bilder/axamer-lizum.jpg", pisteMap: "bilder/axamer-lizum-map.jpg", website: "https://www.axamer-lizum.at", highlights: "Das 'Weiße Dachl' von Innsbruck. Ehemaliger Austragungsort der Olympischen Winterspiele mit spektakulärer Bergkulisse.", tags: ["Österreich", "Schneesicher", "Off-Piste", "Sonnig"] },
    { id: 100, name: "Hochzeiger (Pitztal)", coords: [47.1650, 10.7712], pisteKm: 40, lifts: 9, elevation: 2450, priceLevel: 2, skipass: "66 €", img: "bilder/hochzeiger.jpg", pisteMap: "bilder/hochzeiger-map.jpg", website: "https://www.hochzeiger.com", highlights: "Sonniges Familien-Skigebiet am Eingang des Pitztals. Sehr beliebt für seine breiten Pisten und den Zirbenpark.", tags: ["Österreich", "Familien", "Sonnig", "klein"] },
    { id: 101, name: "Mayrhofen (Penken/Ahorn)", coords: [47.1628, 11.8624], pisteKm: 142, lifts: 58, elevation: 2500, priceLevel: 3, skipass: "72,50 €", img: "bilder/mayrhofen.jpg", pisteMap: "bilder/mayrhofen-map.jpg", website: "https://www.mayrhofen.at", highlights: "Legendäres Skigebiet mit der steilsten Piste Österreichs ('Harakiri') und riesigem Snowpark.", tags: ["Österreich", "Großes Skigebiet", "Après-Ski", "Snowpark"] },
    { id: 102, name: "Hochfügen-Hochzillertal", coords: [47.2663, 11.7770], pisteKm: 93, lifts: 39, elevation: 2378, priceLevel: 3, skipass: "79 €", img: "bilder/hochfuegen.jpg", pisteMap: "bilder/hochfuegen-map.jpg", website: "https://www.hochfuegenski.com", highlights: "Hochalpines Freeride-Paradies und perfekt präparierte Pisten bis auf knapp 2.400 Meter.", tags: ["Österreich", "Schneesicher", "Off-Piste", "Hütten"] },
    
    // ==========================================
    // --- SCHWEIZ ---
    // ==========================================
    { id: 4, name: "Zermatt", coords: [46.0207, 7.7491], pisteKm: 360, lifts: 52, elevation: 3899, priceLevel: 3, skipass: "105 CHF", img: "bilder/zermatt.jpg", pisteMap: "bilder/zermatt-map.jpg", website: "https://www.zermatt.ch", highlights: "Skifahren vor der Kulisse des Matterhorns. Höchstgelegenes Skigebiet Europas.", tags: ["Schweiz", "Italien", "Gletscher", "moderne Liftanlagen"] },
    { id: 22, name: "Davos Klosters", coords: [46.8027, 9.8360], pisteKm: 269, lifts: 54, elevation: 2844, priceLevel: 3, skipass: "85 CHF", img: "bilder/davos.jpg", pisteMap: "bilder/davos-map.jpg", website: "https://www.davosklostersmountains.ch", highlights: "Höchstgelegene Stadt Europas. Skigebiet Parsenn ist ein Klassiker und sehr weitläufig.", tags: ["Schweiz", "Großes Skigebiet", "Off-Piste"] },
    { id: 23, name: "Engelberg-Titlis", coords: [46.8200, 8.4029], pisteKm: 82, lifts: 23, elevation: 3020, priceLevel: 3, skipass: "75 CHF", img: "bilder/engelberg.jpg", pisteMap: "bilder/engelberg-map.jpg", website: "https://www.titlis.ch", highlights: "Zentralschweizer Freeride-Hotspot. Der Titlis-Gletscher garantiert lange Saisons.", tags: ["Schweiz", "Off-Piste", "Gletscher"] },
    { id: 24, name: "St. Moritz (Corviglia)", coords: [46.4908, 9.8355], pisteKm: 155, lifts: 22, elevation: 3057, priceLevel: 3, skipass: "95 CHF", img: "bilder/stmoritz.jpg", pisteMap: "bilder/stmoritz-map.jpg", website: "https://www.mountains.ch", highlights: "Der Inbegriff für Luxus und Jetset im Wintersport. Bietet grandiose Pisten, viel Sonne und edle Gastronomie.", tags: ["Schweiz", "Weltcup", "Sonnig"] },
    { id: 34, name: "Laax", coords: [46.8360, 9.2290], pisteKm: 224, lifts: 28, elevation: 3018, priceLevel: 3, skipass: "95 CHF", img: "bilder/laax.jpg", pisteMap: "bilder/laax-map.jpg", website: "https://www.laax.com", highlights: "Europas Freestyle-Mekka Nummer eins. Bietet gigantische Snowparks und einen urbanen Vibe.", tags: ["Schweiz", "Off-Piste", "Großes Skigebiet"] },
    { id: 35, name: "Arosa Lenzerheide", coords: [46.7500, 9.5800], pisteKm: 225, lifts: 43, elevation: 2865, priceLevel: 3, skipass: "89 CHF", img: "bilder/arosa.jpg", pisteMap: "bilder/arosa-map.jpg", website: "https://arosalenzerheide.swiss", highlights: "Zwei durch die spektakuläre Urdenbahn verbundene Täler. Viele gemütliche Bergrestaurants.", tags: ["Schweiz", "Familien", "Großes Skigebiet", "Sonnig"] },
    { id: 36, name: "Grindelwald (Jungfrau)", coords: [46.6240, 8.0340], pisteKm: 211, lifts: 40, elevation: 2970, priceLevel: 3, skipass: "79 CHF", img: "bilder/grindelwald.jpg", pisteMap: "bilder/grindelwald-map.jpg", website: "https://www.jungfrau.ch", highlights: "Skifahren vor dem weltberühmten Dreigestirn Eiger, Mönch und Jungfrau. Legendäre Lauberhorn-Abfahrt.", tags: ["Schweiz", "Weltcup", "Großes Skigebiet"] },
    { id: 37, name: "Crans-Montana", coords: [46.3110, 7.4800], pisteKm: 140, lifts: 19, elevation: 2927, priceLevel: 3, skipass: "89 CHF", img: "bilder/crans-montana.jpg", pisteMap: "bilder/crans-montana-map.jpg", website: "https://www.crans-montana.ch", highlights: "Ein sonniges Hochplateau über dem Rhonetal. Bekannt für luxuriöses Flair.", tags: ["Schweiz", "Sonnig", "Familien"] },
    { id: 38, name: "Saas-Fee", coords: [46.1090, 7.9290], pisteKm: 150, lifts: 22, elevation: 3600, priceLevel: 3, skipass: "79 CHF", img: "bilder/saas-fee.jpg", pisteMap: "bilder/saas-fee-map.jpg", website: "https://www.saas-fee.ch", highlights: "Die 'Perle der Alpen' ist ein autofreies Gletscherdorf. Extreme Schneesicherheit.", tags: ["Schweiz", "Gletscher", "Schneesicher"] },
    { id: 39, name: "Verbier (4 Vallées)", coords: [46.0960, 7.3280], pisteKm: 410, lifts: 93, elevation: 3330, priceLevel: 3, skipass: "85 CHF", img: "bilder/verbier.jpg", pisteMap: "bilder/verbier-map.jpg", website: "https://www.verbier.ch", highlights: "Teil der '4 Vallées', ein weltberühmter Hotspot für Freerider und legendäres Après-Ski.", tags: ["Schweiz", "Off-Piste", "Großes Skigebiet", "Après-Ski"] },
    { id: 71, name: "Andermatt - Sedrun", coords: [46.6341, 8.5956], pisteKm: 120, lifts: 22, elevation: 2961, priceLevel: 3, skipass: "95 CHF", img: "bilder/andermatt.jpg", pisteMap: "bilder/andermatt-map.jpg", website: "https://www.andermatt.ch", highlights: "Vollständig modernisiert, extreme Schneesicherheit und riesiges Freeride-Potenzial am Gemsstock.", tags: ["Schweiz", "Off-Piste", "moderne Liftanlagen"] },
    { id: 72, name: "Adelboden - Lenk", coords: [46.4936, 7.5587], pisteKm: 200, lifts: 70, elevation: 2350, priceLevel: 3, skipass: "79 CHF", img: "bilder/adelboden.jpg", pisteMap: "bilder/adelboden-map.jpg", website: "https://www.adelboden-lenk.ch", highlights: "Heimat des legendären Chuenisbärgli Weltcup-Riesenslaloms und urgemütlichen Schweizer Hütten.", tags: ["Schweiz", "Weltcup", "Hütten"] },
    { id: 73, name: "Gstaad (Saanen)", coords: [46.4735, 7.2847], pisteKm: 200, lifts: 42, elevation: 3000, priceLevel: 3, skipass: "85 CHF", img: "bilder/gstaad.jpg", pisteMap: "bilder/gstaad-map.jpg", website: "https://www.gstaad.ch", highlights: "Sanfte Hügel, Gletscherskilauf auf dem Glacier 3000 und extremer Luxus im Tal.", tags: ["Schweiz", "Familien", "Gletscher"] },
    { id: 74, name: "Grimentz - Zinal", coords: [46.1738, 7.5707], pisteKm: 115, lifts: 21, elevation: 2900, priceLevel: 2, skipass: "75 CHF", img: "bilder/grimentz.jpg", pisteMap: "bilder/grimentz-map.jpg", website: "https://www.valdanniviers.ch", highlights: "Spektakuläre Freeride-Hänge fernab vom Massentourismus, verbunden durch eine gigantische Gondel.", tags: ["Schweiz", "Off-Piste", "Schneesicher"] },
    { id: 99, name: "Klewenalp-Stockhütte", coords: [46.9380, 8.4735], pisteKm: 40, lifts: 14, elevation: 1938, priceLevel: 2, skipass: "61 CHF", img: "bilder/klewenalp.jpg", pisteMap: "bilder/klewenalp-map.jpg", website: "https://www.klewenalp.ch", highlights: "Wunderschönes, familienfreundliches Skigebiet mit gigantischem Blick über den Vierwaldstättersee.", tags: ["Schweiz", "Familien", "Sonnig", "klein"] },

    // ==========================================
    // --- DEUTSCHLAND ---
    // ==========================================
    { id: 46, name: "Feldberg (Schwarzwald)", coords: [47.8736, 8.0311], pisteKm: 63, lifts: 38, elevation: 1448, priceLevel: 1, skipass: "48 €", img: "bilder/feldberg.jpg", pisteMap: "bilder/feldberg-map.jpg", website: "https://www.liftverbund-feldberg.de", highlights: "Das größte Skigebiet im Schwarzwald. Bietet tolle Pisten für Familien.", tags: ["Deutschland", "Familien", "Günstig"] },
    { id: 47, name: "Skiliftkarussell Winterberg", coords: [51.1969, 8.5303], pisteKm: 27, lifts: 27, elevation: 820, priceLevel: 1, skipass: "48 €", img: "bilder/winterberg.jpg", pisteMap: "bilder/winterberg-map.jpg", website: "https://www.skiliftkarussell.de", highlights: "Das bekannteste Skigebiet im Sauerland. Sehr modern ausgebaut, bietet fantastisches Flutlichtfahren.", tags: ["Deutschland", "Familien", "Après-Ski", "klein"] },
    { id: 75, name: "Zugspitze", coords: [47.4211, 10.9853], pisteKm: 20, lifts: 10, elevation: 2720, priceLevel: 2, skipass: "66 €", img: "bilder/zugspitze.jpg", pisteMap: "bilder/zugspitze-map.jpg", website: "https://zugspitze.de", highlights: "Deutschlands höchstes Skigebiet mit fantastischem Naturschnee auf dem Platt.", tags: ["Deutschland", "Schneesicher", "klein"] },
    { id: 76, name: "Oberjoch (Bad Hindelang)", coords: [47.5147, 10.4022], pisteKm: 32, lifts: 5, elevation: 1559, priceLevel: 1, skipass: "50 €", img: "bilder/oberjoch.jpg", pisteMap: "bilder/oberjoch-map.jpg", website: "https://www.bergbahnen-hindelang-oberjoch.de", highlights: "Extrem familienfreundlich und Deutschlands höchstgelegenes echtes Ski-Dorf.", tags: ["Deutschland", "Familien", "klein", "moderne Liftanlagen"] },
    { id: 77, name: "Ofterschwang - Gunzesried", coords: [47.4967, 10.2367], pisteKm: 18, lifts: 7, elevation: 1405, priceLevel: 1, skipass: "48 €", img: "bilder/ofterschwang.jpg", pisteMap: "bilder/ofterschwang-map.jpg", website: "https://www.go-ofterschwang.de", highlights: "Regelmäßiger Ausrichter des Damen-Skiweltcups im Allgäu.", tags: ["Deutschland", "klein", "Weltcup", "Familien"] },
    { id: 78, name: "Steibis (Skiarena)", coords: [47.5192, 10.0242], pisteKm: 18, lifts: 8, elevation: 1470, priceLevel: 1, skipass: "49 €", img: "bilder/steibis.jpg", pisteMap: "bilder/steibis-map.jpg", website: "https://www.imbergbahn.de", highlights: "Schönes Familiengebiet im Allgäu mit sonnigen Hängen.", tags: ["Deutschland", "klein", "Familien", "Günstig"] },
    { id: 95, name: "Nebelhorn (Oberstdorf)", coords: [47.4124, 10.3341], pisteKm: 13, lifts: 6, elevation: 2224, priceLevel: 2, skipass: "69 €", img: "bilder/nebelhorn.jpg", pisteMap: "bilder/nebelhorn-map.jpg", website: "https://www.ok-bergbahnen.com", highlights: "Die höchste Bergbahn des Allgäus und legendär lange, steile Talabfahrt nach Oberstdorf.", tags: ["Deutschland", "klein", "Schneesicher"] },
    { id: 96, name: "Fellhorn / Kanzelwand", coords: [47.3512, 10.2604], pisteKm: 36, lifts: 14, elevation: 1967, priceLevel: 2, skipass: "69 €", img: "bilder/fellhorn.jpg", pisteMap: "bilder/fellhorn-map.jpg", website: "https://www.ok-bergbahnen.com", highlights: "Grenzübergreifendes Skifahren (DE/AT) und größtes Skigebiet in der Oberstdorf-Region.", tags: ["Deutschland", "Österreich", "moderne Liftanlagen", "Familien"] },

    // ==========================================
    // --- ITALIEN ---
    // ==========================================
    { id: 8, name: "Cortina d'Ampezzo", coords: [46.5376, 12.1357], pisteKm: 120, lifts: 30, elevation: 2835, priceLevel: 3, skipass: "77 €", img: "bilder/cortina.jpg", pisteMap: "bilder/cortina-map.jpg", website: "https://www.dolomitisuperski.com/cortina", highlights: "Das Juwel der Dolomiten. Legendäre Weltcup-Pisten eingebettet in die markanten Felsformationen.", tags: ["Italien", "Weltcup", "Sonnig"] },
    { id: 33, name: "Dolomiti Superski", coords: [46.5000, 11.8333], pisteKm: 1200, lifts: 450, elevation: 3269, priceLevel: 3, skipass: "83 €", img: "bilder/dolomiti.jpg", pisteMap: "bilder/dolomiti-map.jpg", website: "https://www.dolomitisuperski.com", highlights: "Gigantischer Skiverbund in den italienischen Dolomiten (UNESCO-Welterbe).", tags: ["Italien", "Großes Skigebiet", "Gletscher", "Familien"] },
    { id: 79, name: "Ski Civetta", coords: [46.3984, 12.0664], pisteKm: 80, lifts: 23, elevation: 2100, priceLevel: 2, skipass: "70 €", img: "bilder/civetta.jpg", pisteMap: "bilder/civetta-map.jpg", website: "https://www.skicivetta.com", highlights: "Traumhaftes Dolomiten-Panorama unter der gigantischen Civetta Nordwestwand.", tags: ["Italien", "Hütten", "Familien"] },
    { id: 80, name: "Passo San Pellegrino", coords: [46.3789, 11.7916], pisteKm: 67, lifts: 15, elevation: 2513, priceLevel: 2, skipass: "68 €", img: "bilder/pellegrino.jpg", pisteMap: "bilder/pellegrino-map.jpg", website: "https://www.passosanpellegrino.it", highlights: "Sehr breite und sonnige Pisten, ideal für Carving-Fans.", tags: ["Italien", "Sonnig", "moderne Liftanlagen"] },
    { id: 81, name: "Kronplatz (Plan de Corones)", coords: [46.7388, 11.9583], pisteKm: 121, lifts: 32, elevation: 2275, priceLevel: 3, skipass: "77 €", img: "bilder/kronplatz.jpg", pisteMap: "bilder/kronplatz-map.jpg", website: "https://www.kronplatz.com", highlights: "Der modernste Skiberg Südtirols. Glatzköpfiger Berg mit Pisten in alle Himmelsrichtungen.", tags: ["Italien", "moderne Liftanlagen", "Sonnig"] },
    { id: 82, name: "Drei Zinnen Dolomiten", coords: [46.7214, 12.3585], pisteKm: 115, lifts: 31, elevation: 2200, priceLevel: 3, skipass: "77 €", img: "bilder/dreizinnen.jpg", pisteMap: "bilder/dreizinnen-map.jpg", website: "https://www.dreizinnen.com", highlights: "Steilste Holzpiste Italiens und einzigartiger Ausblick auf das Bergmassiv der Drei Zinnen.", tags: ["Italien", "Hütten", "Familien"] },
    { id: 83, name: "Gitschberg Jochtal", coords: [46.8227, 11.6441], pisteKm: 55, lifts: 15, elevation: 2510, priceLevel: 2, skipass: "65 €", img: "bilder/gitschberg.jpg", pisteMap: "bilder/gitschberg-map.jpg", website: "https://www.gitschberg-jochtal.com", highlights: "Besonders familienfreundliches Skigebiet mit urigen Almhütten am Eingang des Pustertals.", tags: ["Italien", "Familien", "Hütten"] },
    { id: 84, name: "Madonna di Campiglio", coords: [46.2269, 10.8258], pisteKm: 150, lifts: 57, elevation: 2504, priceLevel: 3, skipass: "80 €", img: "bilder/campiglio.jpg", pisteMap: "bilder/campiglio-map.jpg", website: "https://www.campigliodolomiti.it", highlights: "Mondäner Weltcup-Ort in den Brenta-Dolomiten mit perfekt präparierten Pisten.", tags: ["Italien", "Weltcup", "Großes Skigebiet"] },
    { id: 85, name: "Bormio", coords: [46.4692, 10.3752], pisteKm: 50, lifts: 15, elevation: 3012, priceLevel: 2, skipass: "60 €", img: "bilder/bormio.jpg", pisteMap: "bilder/bormio-map.jpg", website: "https://www.bormioski.eu", highlights: "Extreme Höhendifferenz und die gefürchtete Weltcup-Abfahrt 'Stelvio'.", tags: ["Italien", "Weltcup", "Schneesicher"] },
    { id: 86, name: "Livigno", coords: [46.5385, 10.1357], pisteKm: 115, lifts: 32, elevation: 2798, priceLevel: 2, skipass: "65 €", img: "bilder/livigno.jpg", pisteMap: "bilder/livigno-map.jpg", website: "https://www.livigno.eu", highlights: "Zollfreies Shopping und aufgrund der hochalpinen, isolierten Lage extrem schneesicheres 'Klein-Tibet'.", tags: ["Italien", "Schneesicher", "Sonnig"] },
    { id: 87, name: "Artesina (Mondolè Ski)", coords: [44.2541, 7.7652], pisteKm: 130, lifts: 24, elevation: 2085, priceLevel: 1, skipass: "48 €", img: "bilder/artesina.jpg", pisteMap: "bilder/artesina-map.jpg", website: "https://www.artesina.it", highlights: "Unbekanntes, aber riesiges Skigebiet im südlichen Piemont nahe der Mittelmeerküste.", tags: ["Italien", "Günstig", "Großes Skigebiet"] },

    // ==========================================
    // --- FRANKREICH ---
    // ==========================================
    { id: 7, name: "Les 3 Vallées", coords: [45.2980, 6.5796], pisteKm: 600, lifts: 160, elevation: 3230, priceLevel: 3, skipass: "83 €", img: "bilder/les3vallees.jpg", pisteMap: "bilder/les3vallees-map.jpg", website: "https://www.les3vallees.com", highlights: "Das größte zusammenhängende Skigebiet der Welt.", tags: ["Frankreich", "Großes Skigebiet", "Gletscher", "moderne Liftanlagen"] },
    { id: 40, name: "Avoriaz (Portes du Soleil)", coords: [46.1930, 6.7720], pisteKm: 600, lifts: 208, elevation: 2460, priceLevel: 2, skipass: "68 €", img: "bilder/avoriaz.jpg", pisteMap: "bilder/avoriaz-map.jpg", website: "https://www.avoriaz.com", highlights: "Zentraler Ort des grenzübergreifenden Verbunds 'Portes du Soleil'. Autofrei und Ski-in/Ski-out überall.", tags: ["Frankreich", "Schweiz", "Großes Skigebiet", "Familien"] },
    { id: 41, name: "Chamonix-Mont-Blanc", coords: [45.9230, 6.8690], pisteKm: 119, lifts: 46, elevation: 3842, priceLevel: 2, skipass: "74 €", img: "bilder/chamonix.jpg", pisteMap: "bilder/chamonix-map.jpg", website: "https://www.chamonix.com", highlights: "Die Wiege des Alpinismus am Fuße des Mont Blanc. Einzigartige Gletscherabfahrten.", tags: ["Frankreich", "Off-Piste", "Gletscher"] },
    { id: 42, name: "Tignes (Espace Killy)", coords: [45.4680, 6.9050], pisteKm: 300, lifts: 78, elevation: 3456, priceLevel: 2, skipass: "66 €", img: "bilder/tignes.jpg", pisteMap: "bilder/tignes-map.jpg", website: "https://www.tignes.net", highlights: "Extrem hochgelegenes und schneesicheres Gebiet mit Gletscherskilauf und gigantischem Terrain.", tags: ["Frankreich", "Gletscher", "Schneesicher", "Großes Skigebiet"] },
    { id: 43, name: "Les Deux Alpes", coords: [44.9800, 6.1330], pisteKm: 200, lifts: 43, elevation: 3568, priceLevel: 1, skipass: "60 €", img: "bilder/les-deux-alpes.jpg", pisteMap: "bilder/les-deux-alpes-map.jpg", website: "https://www.les2alpes.com", highlights: "Verfügt über das größte befahrbare Gletschergebiet Europas. Sehr lebhaftes Après-Ski-Treiben.", tags: ["Frankreich", "Gletscher", "Schneesicher", "Après-Ski"] },
    { id: 44, name: "Alpe d'Huez", coords: [45.0900, 6.0680], pisteKm: 250, lifts: 69, elevation: 3330, priceLevel: 2, skipass: "62 €", img: "bilder/alpe-dhuez.jpg", pisteMap: "bilder/alpe-dhuez-map.jpg", website: "https://www.alpedhuez.com", highlights: "Die 'Insel an der Sonne'. Berühmt für die legendäre 'Sarenne'-Piste.", tags: ["Frankreich", "Großes Skigebiet", "Sonnig"] },
    { id: 88, name: "La Clusaz", coords: [45.9038, 6.4239], pisteKm: 125, lifts: 49, elevation: 2600, priceLevel: 2, skipass: "55 €", img: "bilder/laclusaz.jpg", pisteMap: "bilder/laclusaz-map.jpg", website: "https://www.laclusaz.com", highlights: "Ein authentisches französisches Bergdorf, bekannt als Wiege des Freeride und Freestyle in Frankreich.", tags: ["Frankreich", "Off-Piste", "Hütten"] },
    { id: 89, name: "Les Saisies", coords: [45.7592, 6.5367], pisteKm: 77, lifts: 30, elevation: 1940, priceLevel: 2, skipass: "49 €", img: "bilder/lessaisies.jpg", pisteMap: "bilder/lessaisies-map.jpg", website: "https://www.lessaisies.com", highlights: "Fantastische Aussichten auf den Mont Blanc, sehr sonnig und perfekt für Familien.", tags: ["Frankreich", "Familien", "Sonnig", "Günstig"] },
    { id: 90, name: "Evasion Mont Blanc (Megève)", coords: [45.8569, 6.6178], pisteKm: 400, lifts: 107, elevation: 2353, priceLevel: 3, skipass: "63 €", img: "bilder/evasion.jpg", pisteMap: "bilder/evasion-map.jpg", website: "https://evasionmontblanc.com", highlights: "Malerische Waldabfahrten und Luxus-Charme rund um den edlen Skiort Megève.", tags: ["Frankreich", "Großes Skigebiet", "Hütten"] },
    { id: 91, name: "Le Grand Massif (Flaine)", coords: [46.0064, 6.6908], pisteKm: 265, lifts: 62, elevation: 2480, priceLevel: 2, skipass: "60 €", img: "bilder/grandmassif.jpg", pisteMap: "bilder/grandmassif-map.jpg", website: "https://www.grand-massif.com", highlights: "Architektonisch einmaliger Skiort (Flaine) im Bauhaus-Stil inmitten eines gigantischen Kessels.", tags: ["Frankreich", "Großes Skigebiet", "Schneesicher"] },
    { id: 92, name: "Les Arcs (Paradiski)", coords: [45.5722, 6.8041], pisteKm: 425, lifts: 130, elevation: 3226, priceLevel: 3, skipass: "70 €", img: "bilder/lesarcs.jpg", pisteMap: "bilder/lesarcs-map.jpg", website: "https://www.lesarcs.com", highlights: "Teil des riesigen Paradiski-Verbunds, extrem schneesicher und bekannt für die Speed-Ski-Strecke.", tags: ["Frankreich", "Großes Skigebiet", "moderne Liftanlagen"] },
    { id: 93, name: "La Plagne (Paradiski)", coords: [45.5033, 6.6742], pisteKm: 225, lifts: 74, elevation: 3250, priceLevel: 3, skipass: "65 €", img: "bilder/laplagne.jpg", pisteMap: "bilder/laplagne-map.jpg", website: "https://www.la-plagne.com", highlights: "Bietet eine olympische Bobbahn und unfassbar viele direkte Ski-in/Ski-out Unterkünfte.", tags: ["Frankreich", "Großes Skigebiet", "Familien"] },
    { id: 94, name: "Vars/Risoul (La Forêt Blanche)", coords: [44.5947, 6.6892], pisteKm: 185, lifts: 36, elevation: 2750, priceLevel: 2, skipass: "53 €", img: "bilder/vars.jpg", pisteMap: "bilder/vars-map.jpg", website: "https://www.vars.com", highlights: "Heimat einer der berühmtesten Speedski-Strecken der Welt unter südlicher Sonne.", tags: ["Frankreich", "Sonnig", "Günstig"] },

    // ==========================================
    // --- USA ---
    // ==========================================
    { id: 48, name: "Vail", coords: [39.6384, -106.3742], pisteKm: 234, lifts: 31, elevation: 3527, priceLevel: 3, skipass: "279 USD", img: "bilder/vail.jpg", pisteMap: "bilder/vail-map.jpg", website: "https://www.vail.com", highlights: "Berühmt für die riesigen, pulverschneereichen 'Back Bowls'.", tags: ["USA", "Großes Skigebiet", "Off-Piste"] },
    { id: 49, name: "Jackson Hole", coords: [43.5875, -110.8279], pisteKm: 130, lifts: 13, elevation: 3185, priceLevel: 3, skipass: "255 USD", img: "bilder/jacksonhole.jpg", pisteMap: "bilder/jacksonhole-map.jpg", website: "https://www.jacksonhole.com", highlights: "Ein Traum für Könner und Freerider mit extrem steilem Terrain und authentischem Cowboy-Flair.", tags: ["USA", "Off-Piste", "Schneesicher"] },
    { id: 50, name: "Park City", coords: [40.6514, -111.5080], pisteKm: 250, lifts: 41, elevation: 3048, priceLevel: 3, skipass: "289 USD", img: "bilder/parkcity.jpg", pisteMap: "bilder/parkcity-map.jpg", website: "https://www.parkcitymountain.com", highlights: "Das größte Skigebiet in den USA. Direkte Anbindung an eine historische Silbergräberstadt.", tags: ["USA", "Großes Skigebiet", "Après-Ski"] },
    { id: 51, name: "Aspen Snowmass", coords: [39.2064, -106.9452], pisteKm: 237, lifts: 20, elevation: 3813, priceLevel: 3, skipass: "244 USD", img: "bilder/aspen.jpg", pisteMap: "bilder/aspen-map.jpg", website: "https://www.aspensnowmass.com", highlights: "Vier verschiedene Skiberge vereint. Prominenz, Champagner-Powder und atemberaubende Natur.", tags: ["USA", "Großes Skigebiet", "Weltcup"] },

    // ==========================================
    // --- KANADA ---
    // ==========================================
    { id: 29, name: "Whistler Blackcomb", coords: [50.1163, -122.9574], pisteKm: 200, lifts: 37, elevation: 2284, priceLevel: 3, skipass: "220 CAD", img: "bilder/whistler.jpg", pisteMap: "bilder/whistler-map.jpg", website: "https://www.whistlerblackcomb.com", highlights: "Das größte Skigebiet Nordamerikas. Spektakuläre Peak 2 Peak Gondel.", tags: ["Kanada", "Großes Skigebiet", "Gletscher", "moderne Liftanlagen"] },
    { id: 30, name: "Lake Louise", coords: [51.4414, -116.1472], pisteKm: 139, lifts: 11, elevation: 2637, priceLevel: 2, skipass: "155 CAD", img: "bilder/lakelouise.jpg", pisteMap: "bilder/lakelouise-map.jpg", website: "https://www.skilouise.com", highlights: "Atemberaubende Kulisse im Banff Nationalpark mit Blick auf den Victoria Gletscher.", tags: ["Kanada", "Familien", "Weltcup"] },
    { id: 31, name: "Banff Sunshine", coords: [51.1141, -115.7628], pisteKm: 109, lifts: 12, elevation: 2730, priceLevel: 2, skipass: "165 CAD", img: "bilder/banff.jpg", pisteMap: "bilder/banff-map.jpg", website: "https://www.skibanff.com", highlights: "Liegt hoch oben an der kontinentalen Wasserscheide. Bietet extreme Schneesicherheit.", tags: ["Kanada", "Schneesicher", "Off-Piste"] },
    { id: 32, name: "Revelstoke", coords: [50.9584, -118.1634], pisteKm: 55, lifts: 5, elevation: 2225, priceLevel: 3, skipass: "179 CAD", img: "bilder/revelstoke.jpg", pisteMap: "bilder/revelstoke-map.jpg", website: "https://www.revelstokemountainresort.com", highlights: "Hält den Rekord für die größte Höhendifferenz in Nordamerika (1.713 m). Ein Traum für Freerider.", tags: ["Kanada", "Off-Piste", "Schneesicher"] },

    // ==========================================
    // --- JAPAN ---
    // ==========================================
    { id: 25, name: "Niseko United", coords: [42.8631, 140.6972], pisteKm: 47, lifts: 30, elevation: 1200, priceLevel: 3, skipass: "9500 ¥", img: "bilder/niseko.jpg", pisteMap: "bilder/niseko-map.jpg", website: "https://www.niseko.ne.jp", highlights: "Weltbekannt für unfassbare Mengen an extrem trockenem 'Japow' (Japan Powder).", tags: ["Japan", "Off-Piste", "Schneesicher"] },
    { id: 26, name: "Hakuba Valley", coords: [36.6980, 137.8639], pisteKm: 130, lifts: 104, elevation: 1831, priceLevel: 2, skipass: "8500 ¥", img: "bilder/hakuba.jpg", pisteMap: "bilder/hakuba-map.jpg", website: "https://www.hakubavalley.com", highlights: "Austragungsort der Olympischen Spiele 1998. Zehn verschiedene Skigebiete in einem Tal.", tags: ["Japan", "Großes Skigebiet", "Familien"] },
    { id: 27, name: "Nozawa Onsen", coords: [36.9248, 138.4503], pisteKm: 50, lifts: 20, elevation: 1650, priceLevel: 2, skipass: "6800 ¥", img: "bilder/nozawa.jpg", pisteMap: "bilder/nozawa-map.jpg", website: "https://en.nozawaski.com/", highlights: "Ein traditionelles japanisches Dorf voller heißer Quellen (Onsen).", tags: ["Japan", "Familien", "Après-Ski"] },
    { id: 28, name: "Rusutsu", coords: [42.7448, 140.9026], pisteKm: 42, lifts: 18, elevation: 994, priceLevel: 3, skipass: "9800 ¥", img: "bilder/rusutsu.jpg", pisteMap: "bilder/rusutsu-map.jpg", website: "https://rusutsu.com", highlights: "Eines der besten Gebiete für Tree-Skiing weltweit. Liftanlagen direkt durch Wälder.", tags: ["Japan", "Off-Piste", "Schneesicher"] },

    // ==========================================
    // --- OZEANIEN ---
    // ==========================================
    { id: 52, name: "Perisher", coords: [-36.4045, 148.4130], pisteKm: 65, lifts: 47, elevation: 2054, priceLevel: 3, skipass: "249 AUD", img: "bilder/perisher.jpg", pisteMap: "bilder/perisher-map.jpg", website: "https://www.perisher.com.au", highlights: "Das größte Skigebiet auf der Südhalbkugel im Kosciuszko-Nationalpark.", tags: ["Australien", "Familien", "Großes Skigebiet"] },
    { id: 53, name: "Thredbo", coords: [-36.5050, 148.3033], pisteKm: 50, lifts: 14, elevation: 2037, priceLevel: 3, skipass: "219 AUD", img: "bilder/thredbo.jpg", pisteMap: "bilder/thredbo-map.jpg", website: "https://www.thredbo.com.au", highlights: "Bietet die längsten Abfahrten Australiens und einen lebendigen Skiort.", tags: ["Australien", "Après-Ski"] },
    { id: 54, name: "Treble Cone", coords: [-44.6333, 168.8967], pisteKm: 22, lifts: 4, elevation: 2088, priceLevel: 2, skipass: "160 NZD", img: "bilder/treblecone.jpg", pisteMap: "bilder/treblecone-map.jpg", website: "https://www.treblecone.com", highlights: "Größtes Skigebiet auf Neuseelands Südinsel. Beliebt bei Freeridern mit See-Aussicht.", tags: ["Neuseeland", "Off-Piste"] },
    { id: 55, name: "Coronet Peak", coords: [-44.4250, 168.7361], pisteKm: 40, lifts: 8, elevation: 1649, priceLevel: 2, skipass: "159 NZD", img: "bilder/coronetpeak.jpg", pisteMap: "bilder/coronetpeak-map.jpg", website: "https://www.coronetpeak.co.nz", highlights: "Direkt bei Queenstown gelegen, bekannt für fantastisches Nachtskifahren.", tags: ["Neuseeland", "Après-Ski", "Familien"] },

    // ==========================================
    // --- SKANDINAVIEN ---
    // ==========================================
    { id: 56, name: "Åre", coords: [63.3980, 13.0815], pisteKm: 91, lifts: 31, elevation: 1274, priceLevel: 3, skipass: "645 SEK", img: "bilder/aare.jpg", pisteMap: "bilder/aare-map.jpg", website: "https://www.skistar.com/en/ski-destinations/are/", highlights: "Schwedens größtes Skigebiet. Bietet Weltcup-Abfahrten am See.", tags: ["Schweden", "Weltcup"] },
    { id: 57, name: "Trysil", coords: [61.3148, 12.2536], pisteKm: 78, lifts: 31, elevation: 1100, priceLevel: 3, skipass: "625 NOK", img: "bilder/trysil.jpg", pisteMap: "bilder/trysil-map.jpg", website: "https://www.skistar.com/en/ski-destinations/trysil/", highlights: "Norwegens größtes Skigebiet. Perfekt geformter Skiberg.", tags: ["Norwegen", "Familien"] },
    { id: 58, name: "Levi", coords: [67.8040, 24.8080], pisteKm: 38, lifts: 25, elevation: 531, priceLevel: 2, skipass: "54 €", img: "bilder/levi.jpg", pisteMap: "bilder/levi-map.jpg", website: "https://www.levi.fi/en/", highlights: "Skifahren in Finnisch-Lappland mit magischen Polarlichtern.", tags: ["Finnland", "Nordlichter", "Schneesicher"] },
    { id: 59, name: "Hemsedal", coords: [60.8561, 8.5133], pisteKm: 48, lifts: 20, elevation: 1450, priceLevel: 3, skipass: "625 NOK", img: "bilder/hemsedal.jpg", pisteMap: "bilder/hemsedal-map.jpg", website: "https://www.skistar.com/en/ski-destinations/hemsedal/", highlights: "Die 'Alpen Skandinaviens'. Spektakuläre Felsgipfel und exzellente Off-Piste-Möglichkeiten.", tags: ["Norwegen", "Off-Piste", "Après-Ski"] },
    { id: 60, name: "Sälen", coords: [61.1610, 13.2612], pisteKm: 82, lifts: 86, elevation: 890, priceLevel: 2, skipass: "595 SEK", img: "bilder/saelen.jpg", pisteMap: "bilder/saelen-map.jpg", website: "https://www.skistar.com/en/ski-destinations/salen/", highlights: "Ein gigantischer Verbund aus mehreren Skigebieten in Schweden.", tags: ["Schweden", "Familien"] },
    { id: 61, name: "Ruka", coords: [66.1654, 29.1507], pisteKm: 19, lifts: 22, elevation: 492, priceLevel: 2, skipass: "51 €", img: "bilder/ruka.jpg", pisteMap: "bilder/ruka-map.jpg", website: "https://www.ruka.fi/en/", highlights: "Eines der schneesichersten Gebiete Europas dank der frühen Saison. Beleuchtete Pisten.", tags: ["Finnland", "Schneesicher", "Nordlichter"] }
];

const allTags = [
    "Österreich", "Schweiz", "Frankreich", "Italien", "Deutschland", 
    "USA", "Kanada", "Japan", "Australien", "Neuseeland", "Schweden", "Norwegen", "Finnland", 
    "Nordlichter", "Après-Ski", "Schneesicher", "Gletscher", "Großes Skigebiet", "Familien", 
    "Weltcup", "Off-Piste", "Sonnig", "Günstig", "klein", "Hütten", "moderne Liftanlagen", "Snowpark"
];

const regionData = {
    alpen: {
        name: "Die Alpen",
        subtitle: "Das Herz des europäischen Skisports.",
        heroImg: "bilder/alpen.jpg",
        description: "<p>Die Alpen sind das größte und am besten erschlossene Skigebiet der Welt. Sie erstrecken sich über Frankreich, die Schweiz, Italien, Österreich und Deutschland.</p><p>Was die Alpen so besonders macht, ist die Kombination aus gewaltigen, miteinander verbundenen Skischaukeln, puristischer Hüttenkultur und legendärem Après-Ski. Man kann hier morgens in der Schweiz starten und mittags in Italien speisen.</p>",
        costs: [
            { label: "Skipass (Tag)", value: "60€ - 85€" },
            { label: "Unterkunft (Mittel)", value: "80€ - 150€" },
            { label: "Essen & Trinken", value: "40€ - 80€" },
            { label: "Gesamt ca.", value: "180€ - 315€" }
        ],
        galleryResorts: [1, 33, 7, 4, 75] // Zeigt Arlberg, Dolomiti, 3 Vallees, Zermatt, Zugspitze
    },
    japan: {
        name: "Japan (Japow)",
        subtitle: "Federleichter Pulverschnee und heiße Quellen.",
        heroImg: "bilder/japan.jpg",
        description: "<p>Skifahren in Japan ist ein absolutes Bucket-List-Erlebnis. Aufgrund eisiger Winde aus Sibirien, die über das Japanische Meer wehen, fällt hier unfassbar viel und extrem trockener Schnee.</p><p>Die bekanntesten Gebiete liegen auf der Nordinsel Hokkaido und in den Japanischen Alpen. Ein typischer Skitag endet hier zwingend in einem traditionellen Onsen (Thermalbad).</p>",
        costs: [
            { label: "Skipass (Tag)", value: "50€ - 70€" },
            { label: "Unterkunft (Mittel)", value: "70€ - 150€" },
            { label: "Essen & Trinken", value: "30€ - 60€" },
            { label: "Gesamt ca.", value: "150€ - 280€" }
        ],
        galleryResorts: [25]
    },
    rockies: {
        name: "Rocky Mountains",
        subtitle: "Unendliche Weiten und Heliskiing-Mekka.",
        heroImg: "bilder/rockies.jpg",
        description: "<p>Die Rocky Mountains in Nordamerika bieten ein komplett anderes Flair als Europa. Es gibt kaum Pistenmarkierungen über der Baumgrenze, stattdessen fährst du durch atemberaubende Wälder (Tree-Skiing) oder nutzt gigantische 'Bowls' (Schneekessel).</p><p>Die Liftkarten sind exklusiver, dafür sind Pisten leerer und Heliskiing oder Cat-Skiing ist in Kanada absolut legendär.</p>",
        costs: [
            { label: "Skipass (Tag)", value: "100€ - 250€" },
            { label: "Unterkunft (Mittel)", value: "120€ - 300€" },
            { label: "Essen & Trinken", value: "60€ - 150€" },
            { label: "Gesamt ca.", value: "280€ - 700€" }
        ],
        galleryResorts: [29, 48]
    },
    ozeanien: {
        name: "Ozeanien",
        subtitle: "Skifahren, wenn auf der Nordhalbkugel Sommer ist.",
        heroImg: "bilder/ozeanien.jpg",
        description: "<p>Wenn die Alpen grün sind, erwacht der Winter in den Snowy Mountains (Australien) und den Neuseeländischen Alpen. Eine völlig andere Flora und unglaubliche Ausblicke auf Seen und Meeresbuchten machen Skifahren hier einzigartig.</p><p>Neuseeland punktet mit extremer Natur rund um Queenstown, während Australien mit weitläufigen Hochebenen überrascht.</p>",
        costs: [
            { label: "Skipass (Tag)", value: "80€ - 130€" },
            { label: "Unterkunft (Mittel)", value: "100€ - 200€" },
            { label: "Essen & Trinken", value: "50€ - 90€" },
            { label: "Gesamt ca.", value: "230€ - 420€" }
        ],
        galleryResorts: [] 
    },
    skandinavien: {
        name: "Skandinavien",
        subtitle: "Nordlichter, Fjorde und endloser Winter.",
        heroImg: "bilder/skandinavien.jpg",
        description: "<p>Skifahren im hohen Norden bedeutet majestätische Fjordlandschaften in Norwegen, endlose verschneite Wälder in Schweden und die magischen Polarlichter in Finnisch-Lappland.</p><p>Die Berge hier sind zwar nicht so hoch und alpin wie die Alpen, dafür aber extrem schneesicher. Die kurzen Wintertage machen die Skigebiete durch riesige Flutlichtanlagen zu einem einmaligen Erlebnis.</p>",
        costs: [
            { label: "Skipass (Tag)", value: "50€ - 65€" },
            { label: "Unterkunft (Mittel)", value: "90€ - 180€" },
            { label: "Essen & Trinken", value: "50€ - 100€" },
            { label: "Gesamt ca.", value: "190€ - 345€" }
        ],
        galleryResorts: [] 
    }
};